parent=keycloak.v2
import=common/keycloak

styles=css/styles.css

neteye_version=${env.DNF0\:current}
customer_portal_url=${env.CUSTOMER_PORTAL_URL\:https://siwuerthphoenix.atlassian.net/servicedesk/customer/portals}
