name: Common Pull Request Checks

on:
  pull_request:
    branches:
      - "**"

permissions: write-all

jobs:
  common-pull-request-checks:
    uses: neteye-platform/repo-commons/.github/workflows/common-pull-request-checks.yaml@f54c74169b4fa5420c860a9cc534f3554ba47577 # main
    secrets: inherit
